workflows:
  android-workflow:
    name: Build Android APK
    working_directory: mobile_app_flutter
    environment:
      flutter: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK for Android
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/app-*-release.apk
