// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdCuKkwbgMLXhgJlEP1flXw1TRf2uPJ_4',
    appId: '1:579437156136:web:a2e11a7aabaec9accea21d',
    messagingSenderId: '579437156136',
    projectId: 'krushikadhara07',
    authDomain: 'krushikadhara07.firebaseapp.com',
    storageBucket: 'krushikadhara07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJWwvQcPAO0aZUDpjq6EprYYlVdqEu0U',
    appId: '1:579437156136:android:cf8ba6634169e2becea21d',
    messagingSenderId: '579437156136',
    projectId: 'krushikadhara07',
    storageBucket: 'krushikadhara07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60_4qUIWnoZwTnMkR4e4yyRwo98JtHuQ',
    appId: '1:579437156136:ios:8d6e818bd2373a72cea21d',
    messagingSenderId: '579437156136',
    projectId: 'krushikadhara07',
    storageBucket: 'krushikadhara07.firebasestorage.app',
    iosBundleId: 'com.example.krushikadhara',
  );
}
