org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=1024M -XX:+UseSerialGC -XX:-UseCompressedOops
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
android.enableR8=true
io.flutter.build.impeller=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
