-- Supabase PostgreSQL Schema generated from Mongoose Models

-- Table for ChatHistory.js
-- Table for ChatMessage.js
-- Table for Comment.js
-- Table for CommunityPost.js
-- Table for Crop.js
-- Table for CropCalendar.js
-- Table for Equipment.js
-- Table for Farmer.js
-- Table for FarmerLocation.js
-- Table for GovernmentScheme.js
-- Table for Loan.js
-- Table for MarketPrice.js
-- Table for Notification.js
-- Table for PestScan.js
-- Table for Post.js
-- Table for Scheme.js
-- Table for User.js
-- Table for WeatherLog.js
